disabled_rules:
    - nesting
    - anyobject_protocol
    - todo
    - type_body_length
    - function_body_length
    - switch_case_alignment
    - identifier_name
    - inclusive_language
    - file_length
    - cyclomatic_complexity
    - discouraged_direct_init
    - trailing_whitespace
    - vertical_whitespace_opening_braces
    - empty_enum_arguments
    - implicit_getter
    - no_extension_access_modifier
    - attributes
    - compiler_protocol_init
    - nslocalizedstring_key
opt_in_rules:
    - todo
    - closing_brace
    - array_init
    - block_based_kvo
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - comma
    - file_header
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - control_statement
    - convenience_type
    - deployment_target
    - discarded_notification_center_observer
    - discouraged_direct_init
    - discouraged_object_literal
    - duplicate_enum_cases
    - duplicate_imports
    - dynamic_inline
    - empty_collection_literal
    - empty_count
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - empty_string
    - explicit_init
    - file_name_no_space
    - first_where
    - flatmap_over_map_reduce
    - for_where
    - force_cast
    - identical_operands
    - inert_defer
    - is_disjoint
    - joined_default_parameter
    - last_where
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_constant
    - legacy_constructor
    - legacy_hashing
    - legacy_multiple
    - legacy_random
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - mark
    - modifier_order
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiple_closures_with_trailing_closure
    - no_fallthrough_only
    - no_space_in_method_call
    - nsobject_prefer_isequal
    - operator_usage_whitespace
    - operator_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - private_action
    - private_outlet
    - private_over_fileprivate
    - prohibited_interface_builder
    - prohibited_super_call
    - protocol_property_accessors_order
    - reduce_boolean
    - reduce_into
    - redundant_discardable_let
    - redundant_nil_coalescing
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_set_access_control
    - redundant_string_enum_value
    - redundant_type_annotation
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - sorted_first_last
    - statement_position
    - switch_case_alignment
    - syntactic_sugar
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - type_name
    - unneeded_break_in_switch
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_capture_list
    - unused_closure_parameter
    - unused_control_flow_label
    - unused_declaration
    - unused_enumerated
    - unused_import
    - unused_optional_binding
    - unused_setter_value
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    - vertical_whitespace_closing_braces
    - void_return
    - yoda_condition
    - empty_xctest_method
    - private_unit_test
    - xctfail_message
    - fallthrough
    - class_delegate_protocol
    - force_try
    - generic_type_name
    - discouraged_optional_boolean

custom_rules:
    vboolean_clear_condition:
        name: "Переусложненное условие"
        regex: "^(?>(?!(as\\?)|(\\?.)).)*((!= true)|(!= false)).*$"
        message: "Используй == true или == false или саму перменную в качестве условия"
        severity: error

    ob_boolean_in_ternar_return:
        name: "Возврат Bool из тернарного оператора"
        regex: "\\? (true : false)|(false : true)"
        message: "Не используй тернарный оператор для возврата Bool"
        severity: error

    ui_magic_numbers:
        name: "Константы без Extension"
        regex: "offset:\\([a-zA-Z+\\- *./]*\\d+.*\\)|equalTo:\\([a-zA-Z+\\- *./]*\\d+.*\\)|equalToConstant:\\([a-zA-Z+\\- *./]*\\d+.*\\)"
        message: "Расширяй Extension"
        severity: error

large_tuple:
    warning: 4
    error: 5

function_parameter_count:
    warning: 15
    error: 15
    ignores_default_parameters: false

line_length:
    warning: 150
    error: 200
    ignores_comments: true
    ignores_urls: true
    ignores_function_declarations: true
    ignores_interpolated_strings: true
